# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170902_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='major',
        ),
        migrations.AddField(
            model_name='project',
            name='dateRangeBegin',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='dateRangeEnd',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(default=b'N/A'),
        ),
        migrations.AddField(
            model_name='project',
            name='majors',
            field=models.ManyToManyField(to='projects.Major'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
