# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171209_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dateRangeBegin',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dateRangeEnd',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='majors',
        ),
        migrations.AddField(
            model_name='project',
            name='major',
            field=models.CharField(default=b'N/A', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
