# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

pipelines:
  default:
    - step:
            image: python:2.7
            script:
              - apt-get update && apt-get install -y python-dev
              - virtualenv --python=/usr/bin/python2.7 env
              - source env/bin/activate
              - pip install -r requirements.txt
              - cp projecthub/components/settings_dev_template.py projecthub/components/settings_dev.py
              - python manage.py test
    - step:
            image: node:9.11.1
            script:
              - npm lint
              - npm install
              - bower install
              - npm test