# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171209_1727'),
        ('authentication', '0002_auto_20171125_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='majors',
            field=models.ManyToManyField(to='projects.Major'),
        ),
    ]
