# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_majors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='majors',
        ),
    ]
